# Generated by Django 5.1.3 on 2024-11-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outflow',
            old_name='descripition',
            new_name='description',
        ),
    ]
