# Generated by Django 5.1.3 on 2024-11-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='products.product', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inflow',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inflow',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='suppliers.supplier', verbose_name='Fornecedor'),
            preserve_default=False,
        ),
    ]
